ALTER TABLE [dbo].[DeprecatedCommonNationalExamCertificate]
    ADD CONSTRAINT [DeprecatedCertificatePK] PRIMARY KEY CLUSTERED ([Year] ASC, [Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

