CREATE TABLE [dbo].[AccountLog] (
    [AccountId]             BIGINT           NOT NULL,
    [VersionId]             INT              NOT NULL,
    [UpdateDate]            DATETIME         NOT NULL,
    [UpdateId]              UNIQUEIDENTIFIER NOT NULL,
    [EditorAccountId]       BIGINT           NULL,
    [EditorIp]              NVARCHAR (255)   NOT NULL,
    [Login]                 NVARCHAR (255)   NOT NULL,
    [PasswordHash]          NVARCHAR (255)   NULL,
    [OrganizationId]        BIGINT           NULL,
    [IsOrganizationOwner]   BIT              NULL,
    [ConfirmYear]           INT              NULL,
    [LastName]              NVARCHAR (255)   NULL,
    [FirstName]             NVARCHAR (255)   NULL,
    [PatronymicName]        NVARCHAR (255)   NULL,
    [Phone]                 NVARCHAR (255)   NULL,
    [Email]                 NVARCHAR (255)   NULL,
    [AdminComment]          NTEXT            NULL,
    [IsActive]              BIT              NOT NULL,
    [Status]                NVARCHAR (255)   NULL,
    [IpAddresses]           NVARCHAR (4000)  NULL,
    [IsActiveChange]        BIT              NOT NULL,
    [IsStatusChange]        BIT              NOT NULL,
    [IsEdit]                BIT              NOT NULL,
    [IsPasswordChange]      BIT              NOT NULL,
    [HasFixedIp]            BIT              NOT NULL,
    [IsVpnEditorIp]         BIT              NOT NULL,
    [HasCrocEgeIntegration] BIT              NULL
);

