CREATE TABLE [dbo].[BatchGUID] (
    [BatchUniqueId] UNIQUEIDENTIFIER NOT NULL,
    [Id]            BIGINT           NOT NULL,
    PRIMARY KEY CLUSTERED ([BatchUniqueId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

