//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Util.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GVUZ.Util.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FormRunHS {
            get {
                object obj = ResourceManager.GetObject("FormRunHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select TOP 1
        ///app.applicationid, app.applicationnumber, app.registrationdate, app.institutionid, app.StatusID
        ///from [dbo].[Application] app
        ///inner join
        ///[dbo].[ImportPackageParsed] tmp
        ///on app.InstitutionId = tmp.InstitutionId
        ///and app.RegistrationDate = tmp.RegistrationDate
        ///and app.ApplicationNumber = tmp.ApplicationNumber
        ///where tmp.id = @id and tmp.RegistrationDate is not null and tmp.ApplicationNumber is not null and tmp.InstitutionID is not null.
        /// </summary>
        internal static string Import_FindApplicationByRecord {
            get {
                return ResourceManager.GetString("Import_FindApplicationByRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[ImportPackageParsed] set [Status] = null, [Comment] = NULL where [Status] = @statusProcessing.
        /// </summary>
        internal static string Import_ResetProcessingStatus {
            get {
                return ResourceManager.GetString("Import_ResetProcessingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    count(*) 
        ///from 
        ///    [dbo].[ImportPackageParsed]
        ///where
        ///    [Status] is null.
        /// </summary>
        internal static string Import_SelectCount {
            get {
                return ResourceManager.GetString("Import_SelectCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///    Id, 
        ///    PackageID, 
        ///    InstitutionID, 
        ///    PackageCreatedDate, 
        ///    PackageModifiedDate, 
        ///    CreatedDate, 
        ///    ModifiedDate, 
        ///    ApplicationNumber, 
        ///    RegistrationDate, 
        ///    DirectionID, 
        ///    EducationFormID, 
        ///    FinanceSourceID, 
        ///    EducationLevelID, 
        ///    Stage, 
        ///    IsBeneficiary, 
        ///    IsForeigner, 
        ///    Status, 
        ///    Comment 
        ///from 
        ///    [dbo].[ImportPackageParsed] 
        ///where 
        ///    [Status] is null 
        ///order by InstitutionID.
        /// </summary>
        internal static string Import_SelectRecords {
            get {
                return ResourceManager.GetString("Import_SelectRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[ImportPackageParsed] set [Status] = @status, [Comment] = @comment, [ModifiedDate] = @modifiedDate where [Id] = @id.
        /// </summary>
        internal static string Import_UpdateRecordStatus {
            get {
                return ResourceManager.GetString("Import_UpdateRecordStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PropertiesHS {
            get {
                object obj = ResourceManager.GetObject("PropertiesHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saveHS {
            get {
                object obj = ResourceManager.GetObject("saveHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StopHS {
            get {
                object obj = ResourceManager.GetObject("StopHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
