//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionRules
    {
        public int RecordID { get; set; }
        public int InstitutionID { get; set; }
        public int Year { get; set; }
        public string FileName { get; set; }
        public string MimeType { get; set; }
        public byte[] File { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
    }
}
