//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationSelectedCompetitiveGroup
    {
        public int ItemID { get; set; }
        public int ApplicationID { get; set; }
        public int CompetitiveGroupID { get; set; }
        public Nullable<short> CalculatedBenefitID { get; set; }
        public Nullable<decimal> CalculatedRating { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Benefit Benefit { get; set; }
        public virtual CompetitiveGroup CompetitiveGroup { get; set; }
    }
}
