//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bulk_Campaign
    {
        public System.Guid Id { get; set; }
        public int InstitutionID { get; set; }
        public int ImportPackageId { get; set; }
        public string UID { get; set; }
        public string Name { get; set; }
        public int YearStart { get; set; }
        public int YearEnd { get; set; }
        public int EducationFormFlag { get; set; }
        public int StatusID { get; set; }
        public bool Additional { get; set; }
        public bool IsFromKrym { get; set; }
    }
}
