//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bulk_Application
    {
        public int ApplicationID { get; set; }
        public Nullable<int> EntrantID { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int InstitutionID { get; set; }
        public Nullable<bool> ApproveInstitutionCount { get; set; }
        public Nullable<bool> NeedHostel { get; set; }
        public Nullable<bool> FirstHigherEducation { get; set; }
        public Nullable<bool> ApprovePersonalData { get; set; }
        public Nullable<bool> FamiliarWithLicenseAndRules { get; set; }
        public Nullable<bool> FamiliarWithAdmissionType { get; set; }
        public Nullable<bool> FamiliarWithOriginalDocumentDeliveryDate { get; set; }
        public int StatusID { get; set; }
        public int WizardStepID { get; set; }
        public int ViolationID { get; set; }
        public string StatusDecision { get; set; }
        public Nullable<System.DateTime> LastCheckDate { get; set; }
        public string ViolationErrors { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public byte SourceID { get; set; }
        public string ApplicationNumber { get; set; }
        public bool OriginalDocumentsReceived { get; set; }
        public Nullable<int> OrderCompetitiveGroupID { get; set; }
        public Nullable<int> OrderOfAdmissionID { get; set; }
        public Nullable<int> OrderCompetitiveGroupItemID { get; set; }
        public Nullable<decimal> OrderCalculatedRating { get; set; }
        public Nullable<short> OrderCalculatedBenefitID { get; set; }
        public Nullable<short> OrderEducationFormID { get; set; }
        public Nullable<short> OrderEducationSourceID { get; set; }
        public Nullable<System.DateTime> LastDenyDate { get; set; }
        public string UID { get; set; }
        public bool IsRequiresBudgetO { get; set; }
        public bool IsRequiresBudgetOZ { get; set; }
        public bool IsRequiresBudgetZ { get; set; }
        public bool IsRequiresPaidO { get; set; }
        public bool IsRequiresPaidOZ { get; set; }
        public bool IsRequiresPaidZ { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> OriginalDocumentsReceivedDate { get; set; }
        public Nullable<System.DateTime> LastEgeDocumentsCheckDate { get; set; }
        public Nullable<int> OrderCompetitiveGroupTargetID { get; set; }
        public bool IsRequiresTargetO { get; set; }
        public bool IsRequiresTargetOZ { get; set; }
        public bool IsRequiresTargetZ { get; set; }
        public Nullable<System.Guid> ApplicationGUID { get; set; }
        public Nullable<int> Priority { get; set; }
        public string EntrantUID { get; set; }
        public int ImportPackageID { get; set; }
    }
}
