//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bulk_ApplicationIndividualAchievements
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public int ImportPackageId { get; set; }
        public int InstitutionId { get; set; }
        public string IAUID { get; set; }
        public string IAName { get; set; }
        public Nullable<decimal> IAMark { get; set; }
        public string EntrantDocumentUID { get; set; }
        public Nullable<int> EntrantDocumentID { get; set; }
        public Nullable<int> InstitutionArchievementID { get; set; }
    }
}
