//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_C
    {
        public Nullable<int> InstitutionID { get; set; }
        public Nullable<int> YearStart { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public string CampaignName { get; set; }
        public Nullable<int> CompetitiveGroupID { get; set; }
        public string CompetitiveGroupName { get; set; }
        public Nullable<int> Course { get; set; }
        public Nullable<int> CompetitiveGroupItemID { get; set; }
        public Nullable<int> CompetitiveGroupTargetID { get; set; }
        public string CompetitiveGroupTargetName { get; set; }
        public Nullable<int> DirectionID { get; set; }
        public string DirectionCode { get; set; }
        public string DirectionName { get; set; }
        public Nullable<int> EducationLevelID { get; set; }
        public string EducationLevelName { get; set; }
        public Nullable<int> EducationFormID { get; set; }
        public string EducationFormName { get; set; }
        public Nullable<int> EducationSourceID { get; set; }
        public string EducationSourceName { get; set; }
        public string ConditionCode { get; set; }
        public Nullable<int> Places { get; set; }
        public Nullable<int> PlacesBase { get; set; }
    }
}
