//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignEducationLevel
    {
        public int CampaignEducationLevelID { get; set; }
        public int CampaignID { get; set; }
        public int Course { get; set; }
        public short EducationLevelID { get; set; }
        public Nullable<bool> PresentInLicense { get; set; }
    
        public virtual AdmissionItemType AdmissionItemType { get; set; }
        public virtual Campaign Campaign { get; set; }
    }
}
