//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSubject
    {
        public int CourseSubjectID { get; set; }
        public int PreparatoryCourseID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string SubjectName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual PreparatoryCourse PreparatoryCourse { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
