//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direction_tmp
    {
        public int DirectionID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string SYS_GUID { get; set; }
        public string EDULEVEL { get; set; }
        public string EDUPROGRAMTYPE { get; set; }
        public string UGSCODE { get; set; }
        public string UGSNAME { get; set; }
        public string QUALIFICATIONCODE { get; set; }
        public string QUALIFICATIONNAME { get; set; }
        public string PERIOD { get; set; }
        public string EDU_DIRECTORY { get; set; }
        public string EDUPR_ADDITIONAL { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string NewCode { get; set; }
    }
}
