//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EduLevelDocumentType
    {
        public int ID { get; set; }
        public int LevelID { get; set; }
        public int DocumentTypeId { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual EduLevels EduLevels { get; set; }
    }
}
