//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EduLevelsToUgsCode
    {
        public short EducationLevelId { get; set; }
        public string QualificationCode { get; set; }
    
        public virtual AdmissionItemType AdmissionItemType { get; set; }
    }
}
