//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportPackage
    {
        public int PackageID { get; set; }
        public int InstitutionID { get; set; }
        public int TypeID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastDateChanged { get; set; }
        public int StatusID { get; set; }
        public string Comment { get; set; }
        public string PackageData { get; set; }
        public string ProcessResultInfo { get; set; }
        public Nullable<int> CheckStatusID { get; set; }
        public string CheckResultInfo { get; set; }
        public string ImportedAppIDs { get; set; }
        public string UserLogin { get; set; }
        public string Content { get; set; }
    
        public virtual ImportPackageStatus ImportPackageStatus { get; set; }
        public virtual ImportPackageType ImportPackageType { get; set; }
        public virtual Institution Institution { get; set; }
    }
}
