//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Data.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class OlympicType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OlympicType()
        {
            this.BenefitItemCOlympicType = new HashSet<BenefitItemCOlympicType>();
            this.OlympicTypeProfile = new HashSet<OlympicTypeProfile>();
        }
    
        public int OlympicID { get; set; }

        [DisplayName("Наименование олимпиады")]
        public string Name { get; set; }
        public Nullable<int> OlympicNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }

        [DisplayName("Год олимпиады")]
        public int OlympicYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BenefitItemCOlympicType> BenefitItemCOlympicType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OlympicTypeProfile> OlympicTypeProfile { get; set; }
    }
}
