//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecomendedLists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecomendedLists()
        {
            this.RecomendedListsHistory = new HashSet<RecomendedListsHistory>();
        }
    
        public int RecListID { get; set; }
        public int InstitutionID { get; set; }
        public int CampaignID { get; set; }
        public int EduLevelID { get; set; }
        public int EduFormID { get; set; }
        public int CompetitiveGroupID { get; set; }
        public int DirectionID { get; set; }
        public byte Stage { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<decimal> Rating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecomendedListsHistory> RecomendedListsHistory { get; set; }
    }
}
