//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_GGV
    {
        public int ЕСРП_ИД { get; set; }
        public string Тип { get; set; }
        public string Категория_ОО { get; set; }
        public string Категория_ОО_2 { get; set; }
        public string ОПФ { get; set; }
        public string Головной_Филиал { get; set; }
        public string Статус_ОО { get; set; }
        public string Обязательность_подключения { get; set; }
        public string Статус_подключения { get; set; }
        public string Этап_подключения { get; set; }
        public string Схема_подключения { get; set; }
        public string Передают_данные_за_ПК_2015_года { get; set; }
        public string Полное_наименование { get; set; }
        public string Поданные_заявления { get; set; }
        public string Поданные_на_бюджет { get; set; }
        public string Поданные_на_платное { get; set; }
        public string Зачисленные { get; set; }
        public string Зачисленные_на_бюджет { get; set; }
        public string Зачисленные_на_платное { get; set; }
        public string КЦП_бюджет { get; set; }
        public string План_на_платное { get; set; }
        public string КЦП___план_на_платное { get; set; }
        public string Закрыли_ПК_2014 { get; set; }
        public string ИНН { get; set; }
        public string КПП { get; set; }
        public string ОГРН { get; set; }
        public string Субъект_РФ { get; set; }
        public string ФО { get; set; }
        public string Статус_лицензии { get; set; }
        public string Учредитель { get; set; }
        public string Головная_организация { get; set; }
        public string CURRENT_DATE { get; set; }
    }
}
