//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP1
    {
        public string ID_ERBD { get; set; }
        public string Vip2015 { get; set; }
        public string Region { get; set; }
        public string Kategoria { get; set; }
    }
}
