//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVUZ.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_HighMarks_2015
    {
        public int id { get; set; }
        public string fio { get; set; }
        public string DocNumber { get; set; }
        public string DocSeries { get; set; }
    }
}
