<?xml version="1.0" encoding="utf-8"?><Database Name="fbs_db" Class="CommonNationalCertificateContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=zubrus.rbc.ru;Failover Partner=zubrus.rbc.ru;Initial Catalog=fbs_db;User ID=fbs" SettingsObjectName="Fbs.Core.Properties.Settings" SettingsPropertyName="FbsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Subject" Member="Subjects">
    <Type Name="Subject" Id="ID1">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="CheckCommonNationalExamCertificateByNumberResults">
    <Type Name="CheckCommonNationalExamCertificateByNumberResult" Id="ID2">
      <Column Name="Number" Type="System.String" DbType="NVarChar(255)" CanBeNull="false" />
      <Column Name="IsOriginal" Type="System.Boolean" DbType="bit" CanBeNull="false" />
      <Column Name="CheckLastName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LastNameIsCorrect" Type="System.Boolean" DbType="bit" CanBeNull="false" />
      <Column Name="CheckFirstName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FirstNameIsCorrect" Type="System.Boolean" DbType="Bit" CanBeNull="false" />
      <Column Name="CheckPatronymicName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PatronymicName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PatronymicNameIsCorrect" Type="System.Boolean" DbType="Bit" CanBeNull="false" />
      <Column Name="IsExist" Type="System.Boolean" DbType="Bit" CanBeNull="false" />
      <Column Name="SubjectId" Storage="_SubjectCode" Type="System.Int32" DbType="int" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(255)" CanBeNull="false" />
      <Column Name="CheckSubjectMark" Storage="_CheckSubjecMark" Type="System.Int32" DbType="int" CanBeNull="true" />
      <Column Name="SubjectMark" Type="System.Int32" DbType="int" CanBeNull="true" />
      <Column Name="SubjectMarkIsCorrect" Type="System.Boolean" DbType="Bit" CanBeNull="false" />
      <Column Name="HasAppeal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeny" Type="System.Boolean" DbType="Bit" CanBeNull="false" />
      <Column Name="DenyComment" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="DenyNewCertificateNumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PassportSeria" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PassportNumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RegionId" Type="System.Int32" DbType="int" CanBeNull="true" />
      <Column Name="RegionName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.UpdateCommonNationalExamCertificateCheckBatch" Method="UpdateCommonNationalExamCertificateCheckBatch" AccessModifier="Internal">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" Direction="InOut" />
    <Parameter Name="login" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ip" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="batch" Type="System.String" DbType="NText" />
	<Parameter Name="filter" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateCommonNationalExamCertificateRequestBatch" Method="UpdateCommonNationalExamCertificateRequestBatch" AccessModifier="Internal">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" Direction="InOut" />
    <Parameter Name="login" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ip" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="batch" Type="System.String" DbType="NText" />
    <Parameter Name="filter" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="IsTypographicNumber" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="year" Type="System.String" DbType="NVarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ExecuteCommonNationalExamCertificateLoadingTask" Method="ExecuteCommonNationalExamCertificateLoadingTask" AccessModifier="Internal">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="editorLogin" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="editorIp" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ExecuteCommonNationalExamCertificateDenyLoadingTask" Method="ExecuteCommonNationalExamCertificateDenyLoadingTask" AccessModifier="Internal">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="editorLogin" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="editorIp" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateEntrantCheckBatch" Method="UpdateEntrantCheckBatch" AccessModifier="Internal">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" Direction="InOut" />
    <Parameter Name="login" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ip" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="batch" Type="System.String" DbType="NText" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateSchoolLeavingCertificateCheckBatch" Method="UpdateSchoolLeavingCertificateCheckBatch" AccessModifier="Internal">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" Direction="InOut" />
    <Parameter Name="login" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ip" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="batch" Type="System.String" DbType="NText" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateCompetitionCertificateRequestBatch" Method="UpdateCompetitionCertificateRequestBatch" AccessModifier="Internal">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" Direction="InOut" />
    <Parameter Name="login" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ip" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="batch" Type="System.String" DbType="NText" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetSubject" Method="GetSubject" AccessModifier="Internal">
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.CheckCommonNationalExamCertificateByNumber" Method="CheckCommonNationalExamCertificateByNumber" AccessModifier="Internal">
    <Parameter Name="number" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="isOriginal" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="checkLastName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="checkFirstName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="checkPatronymicName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="checkSubjectMarks" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="login" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ip" Type="System.String" DbType="NVarChar(255)" />
    <ElementType IdRef="ID2" />
  </Function>
</Database>