ALTER TABLE [dbo].[UserAccountPassword]
    ADD CONSTRAINT [PK171] PRIMARY KEY CLUSTERED ([AccountId] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

