ALTER TABLE [dbo].[OrganizationLog]
    ADD CONSTRAINT [PK71] PRIMARY KEY NONCLUSTERED ([OrganizationId] ASC, [VersionId] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

