ALTER TABLE [dbo].[OrganizationRequest2010]
    ADD CONSTRAINT [PK__OrganizationRequ__2BA54CE1] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

