ALTER TABLE [dbo].[OperatorLog]
    ADD CONSTRAINT [PK_OperatorLog_1] PRIMARY KEY CLUSTERED ([CheckedUserID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

