//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Esrp.GetDataReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetDataSoap", Namespace="urn:ersp:v1")]
    public partial class GetData : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetActualizationDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActualizationData1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrganizationDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrganizationData1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetData() {
            this.Url = global::Esrp.Properties.Settings.Default.Esrp_GetDataReference_GetData;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetActualizationDataCompletedEventHandler GetActualizationDataCompleted;
        
        /// <remarks/>
        public event GetActualizationData1CompletedEventHandler GetActualizationData1Completed;
        
        /// <remarks/>
        public event GetOrganizationDataCompletedEventHandler GetOrganizationDataCompleted;
        
        /// <remarks/>
        public event GetOrganizationData1CompletedEventHandler GetOrganizationData1Completed;
        
        /// <remarks/>
        public event GetUserDetailsCompletedEventHandler GetUserDetailsCompleted;
        
        /// <remarks/>
        public event UpdateUserStatusCompletedEventHandler UpdateUserStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ersp:v1/GetActualizationData", RequestNamespace="urn:ersp:v1", ResponseNamespace="urn:ersp:v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActualizationData GetActualizationData(string userLogin, System.DateTime lastChangeUser, System.DateTime lastChangeOrganization) {
            object[] results = this.Invoke("GetActualizationData", new object[] {
                        userLogin,
                        lastChangeUser,
                        lastChangeOrganization});
            return ((ActualizationData)(results[0]));
        }
        
        /// <remarks/>
        public void GetActualizationDataAsync(string userLogin, System.DateTime lastChangeUser, System.DateTime lastChangeOrganization) {
            this.GetActualizationDataAsync(userLogin, lastChangeUser, lastChangeOrganization, null);
        }
        
        /// <remarks/>
        public void GetActualizationDataAsync(string userLogin, System.DateTime lastChangeUser, System.DateTime lastChangeOrganization, object userState) {
            if ((this.GetActualizationDataOperationCompleted == null)) {
                this.GetActualizationDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActualizationDataOperationCompleted);
            }
            this.InvokeAsync("GetActualizationData", new object[] {
                        userLogin,
                        lastChangeUser,
                        lastChangeOrganization}, this.GetActualizationDataOperationCompleted, userState);
        }
        
        private void OnGetActualizationDataOperationCompleted(object arg) {
            if ((this.GetActualizationDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActualizationDataCompleted(this, new GetActualizationDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="GetActualizationData1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ersp:v1/GetActualizationDataExtended", RequestElementName="GetActualizationDataExtended", RequestNamespace="urn:ersp:v1", ResponseElementName="GetActualizationDataExtendedResponse", ResponseNamespace="urn:ersp:v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetActualizationDataExtendedResult")]
        public ActualizationDataExtended GetActualizationData(string userLogin, System.DateTime lastChangeUser, System.DateTime lastChangeOrganization, int numberOfOrganizations, System.DateTime lastChangeFounder, System.DateTime lastChangeMainOrg) {
            object[] results = this.Invoke("GetActualizationData1", new object[] {
                        userLogin,
                        lastChangeUser,
                        lastChangeOrganization,
                        numberOfOrganizations,
                        lastChangeFounder,
                        lastChangeMainOrg});
            return ((ActualizationDataExtended)(results[0]));
        }
        
        /// <remarks/>
        public void GetActualizationData1Async(string userLogin, System.DateTime lastChangeUser, System.DateTime lastChangeOrganization, int numberOfOrganizations, System.DateTime lastChangeFounder, System.DateTime lastChangeMainOrg) {
            this.GetActualizationData1Async(userLogin, lastChangeUser, lastChangeOrganization, numberOfOrganizations, lastChangeFounder, lastChangeMainOrg, null);
        }
        
        /// <remarks/>
        public void GetActualizationData1Async(string userLogin, System.DateTime lastChangeUser, System.DateTime lastChangeOrganization, int numberOfOrganizations, System.DateTime lastChangeFounder, System.DateTime lastChangeMainOrg, object userState) {
            if ((this.GetActualizationData1OperationCompleted == null)) {
                this.GetActualizationData1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActualizationData1OperationCompleted);
            }
            this.InvokeAsync("GetActualizationData1", new object[] {
                        userLogin,
                        lastChangeUser,
                        lastChangeOrganization,
                        numberOfOrganizations,
                        lastChangeFounder,
                        lastChangeMainOrg}, this.GetActualizationData1OperationCompleted, userState);
        }
        
        private void OnGetActualizationData1OperationCompleted(object arg) {
            if ((this.GetActualizationData1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActualizationData1Completed(this, new GetActualizationData1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ersp:v1/GetOrganizationDataExtended", RequestElementName="GetOrganizationDataExtended", RequestNamespace="urn:ersp:v1", ResponseElementName="GetOrganizationDataExtendedResponse", ResponseNamespace="urn:ersp:v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetOrganizationDataExtendedResult")]
        public OrganizationData[] GetOrganizationData(int orgId, int updateType) {
            object[] results = this.Invoke("GetOrganizationData", new object[] {
                        orgId,
                        updateType});
            return ((OrganizationData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOrganizationDataAsync(int orgId, int updateType) {
            this.GetOrganizationDataAsync(orgId, updateType, null);
        }
        
        /// <remarks/>
        public void GetOrganizationDataAsync(int orgId, int updateType, object userState) {
            if ((this.GetOrganizationDataOperationCompleted == null)) {
                this.GetOrganizationDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrganizationDataOperationCompleted);
            }
            this.InvokeAsync("GetOrganizationData", new object[] {
                        orgId,
                        updateType}, this.GetOrganizationDataOperationCompleted, userState);
        }
        
        private void OnGetOrganizationDataOperationCompleted(object arg) {
            if ((this.GetOrganizationDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrganizationDataCompleted(this, new GetOrganizationDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="GetOrganizationData1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ersp:v1/GetOrganizationData", RequestElementName="GetOrganizationData", RequestNamespace="urn:ersp:v1", ResponseElementName="GetOrganizationDataResponse", ResponseNamespace="urn:ersp:v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetOrganizationDataResult")]
        public OrganizationDataExtended[] GetOrganizationData(string[] userLogins) {
            object[] results = this.Invoke("GetOrganizationData1", new object[] {
                        userLogins});
            return ((OrganizationDataExtended[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOrganizationData1Async(string[] userLogins) {
            this.GetOrganizationData1Async(userLogins, null);
        }
        
        /// <remarks/>
        public void GetOrganizationData1Async(string[] userLogins, object userState) {
            if ((this.GetOrganizationData1OperationCompleted == null)) {
                this.GetOrganizationData1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrganizationData1OperationCompleted);
            }
            this.InvokeAsync("GetOrganizationData1", new object[] {
                        userLogins}, this.GetOrganizationData1OperationCompleted, userState);
        }
        
        private void OnGetOrganizationData1OperationCompleted(object arg) {
            if ((this.GetOrganizationData1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrganizationData1Completed(this, new GetOrganizationData1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ersp:v1/GetUserDetails", RequestNamespace="urn:ersp:v1", ResponseNamespace="urn:ersp:v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserDetails GetUserDetails(string userLogin, int systemID) {
            object[] results = this.Invoke("GetUserDetails", new object[] {
                        userLogin,
                        systemID});
            return ((UserDetails)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserDetailsAsync(string userLogin, int systemID) {
            this.GetUserDetailsAsync(userLogin, systemID, null);
        }
        
        /// <remarks/>
        public void GetUserDetailsAsync(string userLogin, int systemID, object userState) {
            if ((this.GetUserDetailsOperationCompleted == null)) {
                this.GetUserDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserDetailsOperationCompleted);
            }
            this.InvokeAsync("GetUserDetails", new object[] {
                        userLogin,
                        systemID}, this.GetUserDetailsOperationCompleted, userState);
        }
        
        private void OnGetUserDetailsOperationCompleted(object arg) {
            if ((this.GetUserDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserDetailsCompleted(this, new GetUserDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ersp:v1/UpdateUserStatus", RequestNamespace="urn:ersp:v1", ResponseNamespace="urn:ersp:v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateUserStatus(string userLogin, string newStatus) {
            object[] results = this.Invoke("UpdateUserStatus", new object[] {
                        userLogin,
                        newStatus});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserStatusAsync(string userLogin, string newStatus) {
            this.UpdateUserStatusAsync(userLogin, newStatus, null);
        }
        
        /// <remarks/>
        public void UpdateUserStatusAsync(string userLogin, string newStatus, object userState) {
            if ((this.UpdateUserStatusOperationCompleted == null)) {
                this.UpdateUserStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateUserStatus", new object[] {
                        userLogin,
                        newStatus}, this.UpdateUserStatusOperationCompleted, userState);
        }
        
        private void OnUpdateUserStatusOperationCompleted(object arg) {
            if ((this.UpdateUserStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserStatusCompleted(this, new UpdateUserStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActualizationDataExtended))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ersp:v1")]
    public partial class ActualizationData {
        
        private bool shouldRenewUserField;
        
        private bool shouldRenewOrganizationField;
        
        /// <remarks/>
        public bool ShouldRenewUser {
            get {
                return this.shouldRenewUserField;
            }
            set {
                this.shouldRenewUserField = value;
            }
        }
        
        /// <remarks/>
        public bool ShouldRenewOrganization {
            get {
                return this.shouldRenewOrganizationField;
            }
            set {
                this.shouldRenewOrganizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ersp:v1")]
    public partial class UserGroup {
        
        private string codeField;
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ersp:v1")]
    public partial class UserDetails {
        
        private string emailField;
        
        private string firstNameField;
        
        private UserGroup[] groupsField;
        
        private string lastNameField;
        
        private string loginField;
        
        private System.Nullable<int> organizationIDField;
        
        private string patronymicNameField;
        
        private string phoneField;
        
        private string statusField;
        
        private int userIDField;
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public UserGroup[] Groups {
            get {
                return this.groupsField;
            }
            set {
                this.groupsField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> OrganizationID {
            get {
                return this.organizationIDField;
            }
            set {
                this.organizationIDField = value;
            }
        }
        
        /// <remarks/>
        public string PatronymicName {
            get {
                return this.patronymicNameField;
            }
            set {
                this.patronymicNameField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ersp:v1")]
    public partial class OrganizationType {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ersp:v1")]
    public partial class RegionData {
        
        private string codeField;
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganizationDataExtended))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ersp:v1")]
    public partial class OrganizationData {
        
        private int idField;
        
        private string fullNameField;
        
        private string shortNameField;
        
        private int regionIdField;
        
        private int typeIdField;
        
        private int kindIdField;
        
        private string iNNField;
        
        private string oGRNField;
        
        private string ownerDepartmentField;
        
        private bool isPrivateField;
        
        private bool isfilialField;
        
        private string directorPositionField;
        
        private string directorFullNameField;
        
        private bool isAccreditedField;
        
        private string accreditationCertificateField;
        
        private string lawAddressField;
        
        private string factAddressField;
        
        private string phoneCityCodeField;
        
        private string phoneField;
        
        private string faxField;
        
        private string eMailField;
        
        private string siteField;
        
        private int mainIDField;
        
        private int departmentIDField;
        
        private RegionData regionField;
        
        private OrganizationType typeField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
            }
        }
        
        /// <remarks/>
        public int RegionId {
            get {
                return this.regionIdField;
            }
            set {
                this.regionIdField = value;
            }
        }
        
        /// <remarks/>
        public int TypeId {
            get {
                return this.typeIdField;
            }
            set {
                this.typeIdField = value;
            }
        }
        
        /// <remarks/>
        public int KindId {
            get {
                return this.kindIdField;
            }
            set {
                this.kindIdField = value;
            }
        }
        
        /// <remarks/>
        public string INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
            }
        }
        
        /// <remarks/>
        public string OGRN {
            get {
                return this.oGRNField;
            }
            set {
                this.oGRNField = value;
            }
        }
        
        /// <remarks/>
        public string OwnerDepartment {
            get {
                return this.ownerDepartmentField;
            }
            set {
                this.ownerDepartmentField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPrivate {
            get {
                return this.isPrivateField;
            }
            set {
                this.isPrivateField = value;
            }
        }
        
        /// <remarks/>
        public bool Isfilial {
            get {
                return this.isfilialField;
            }
            set {
                this.isfilialField = value;
            }
        }
        
        /// <remarks/>
        public string DirectorPosition {
            get {
                return this.directorPositionField;
            }
            set {
                this.directorPositionField = value;
            }
        }
        
        /// <remarks/>
        public string DirectorFullName {
            get {
                return this.directorFullNameField;
            }
            set {
                this.directorFullNameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAccredited {
            get {
                return this.isAccreditedField;
            }
            set {
                this.isAccreditedField = value;
            }
        }
        
        /// <remarks/>
        public string AccreditationCertificate {
            get {
                return this.accreditationCertificateField;
            }
            set {
                this.accreditationCertificateField = value;
            }
        }
        
        /// <remarks/>
        public string LawAddress {
            get {
                return this.lawAddressField;
            }
            set {
                this.lawAddressField = value;
            }
        }
        
        /// <remarks/>
        public string FactAddress {
            get {
                return this.factAddressField;
            }
            set {
                this.factAddressField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneCityCode {
            get {
                return this.phoneCityCodeField;
            }
            set {
                this.phoneCityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        public int MainID {
            get {
                return this.mainIDField;
            }
            set {
                this.mainIDField = value;
            }
        }
        
        /// <remarks/>
        public int DepartmentID {
            get {
                return this.departmentIDField;
            }
            set {
                this.departmentIDField = value;
            }
        }
        
        /// <remarks/>
        public RegionData Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public OrganizationType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ersp:v1")]
    public partial class OrganizationDataExtended : OrganizationData {
        
        private string requestedLoginField;
        
        /// <remarks/>
        public string RequestedLogin {
            get {
                return this.requestedLoginField;
            }
            set {
                this.requestedLoginField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ersp:v1")]
    public partial class ActualizationDataExtended : ActualizationData {
        
        private bool shouldRenewOrganizationsField;
        
        private bool shouldRenewFounderField;
        
        private bool shouldRenewMainOrgField;
        
        /// <remarks/>
        public bool ShouldRenewOrganizations {
            get {
                return this.shouldRenewOrganizationsField;
            }
            set {
                this.shouldRenewOrganizationsField = value;
            }
        }
        
        /// <remarks/>
        public bool ShouldRenewFounder {
            get {
                return this.shouldRenewFounderField;
            }
            set {
                this.shouldRenewFounderField = value;
            }
        }
        
        /// <remarks/>
        public bool ShouldRenewMainOrg {
            get {
                return this.shouldRenewMainOrgField;
            }
            set {
                this.shouldRenewMainOrgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetActualizationDataCompletedEventHandler(object sender, GetActualizationDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActualizationDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActualizationDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActualizationData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActualizationData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetActualizationData1CompletedEventHandler(object sender, GetActualizationData1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActualizationData1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActualizationData1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActualizationDataExtended Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActualizationDataExtended)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetOrganizationDataCompletedEventHandler(object sender, GetOrganizationDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrganizationDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrganizationDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrganizationData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrganizationData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetOrganizationData1CompletedEventHandler(object sender, GetOrganizationData1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrganizationData1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrganizationData1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrganizationDataExtended[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrganizationDataExtended[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetUserDetailsCompletedEventHandler(object sender, GetUserDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserDetails)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateUserStatusCompletedEventHandler(object sender, UpdateUserStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591