// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FBS.Tests.FBSChecksForIndividuals
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Проверка по сумме баллов")]
    public partial class ПроверкаПоСуммеБалловFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "FBSChecksForIndividuals.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru-RU"), "Проверка по сумме баллов", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line 4
 testRunner.Given("Я захожу под пользователем \"super\"");
#line 5
 testRunner.And("Я открываю страницу Проверка по сумме баллов");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01. Проверка открытия страницы с Проверка по сумме баллов")]
        public virtual void _01_ПроверкаОткрытияСтраницыСПроверкаПоСуммеБаллов()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01. Проверка открытия страницы с Проверка по сумме баллов", ((string[])(null)));
#line 7
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 8
 testRunner.Then("нахожусь на странице Проверка по сумме баллов");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02. Проверка присутствия хлебных крошек на странице Проверка по сумме баллов")]
        public virtual void _02_ПроверкаПрисутствияХлебныхКрошекНаСтраницеПроверкаПоСуммеБаллов()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02. Проверка присутствия хлебных крошек на странице Проверка по сумме баллов", ((string[])(null)));
#line 10
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Text"});
            table1.AddRow(new string[] {
                        "Свидетельства"});
            table1.AddRow(new string[] {
                        "Обезличенные свидетельства"});
            table1.AddRow(new string[] {
                        "Проверка по сумме баллов"});
#line 11
 testRunner.Then("на странице есть следующие хлебные крошки:", ((string)(null)), table1);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03. Проверка полей по умолчанию")]
        public virtual void _03_ПроверкаПолейПоУмолчанию()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03. Проверка полей по умолчанию", ((string[])(null)));
#line 17
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table2.AddRow(new string[] {
                        "selectedOrgName",
                        "Выберите образовательное учреждение"});
            table2.AddRow(new string[] {
                        "cLastName",
                        "Фамилия"});
            table2.AddRow(new string[] {
                        "cFirstName",
                        "Имя"});
            table2.AddRow(new string[] {
                        "cPatronymicName",
                        "Отчество"});
            table2.AddRow(new string[] {
                        "cMarkSum",
                        "Сумма баллов"});
            table2.AddRow(new string[] {
                        "CodeNumberTextBox",
                        ""});
#line 18
 testRunner.Then("вижу в полях следующие данные:", ((string)(null)), table2);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04. Проверка обязательный полей")]
        public virtual void _04_ПроверкаОбязательныйПолей()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04. Проверка обязательный полей", ((string[])(null)));
#line 27
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 28
 testRunner.When("нажимаю кнопку \"Выбрать\"");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table3.AddRow(new string[] {
                        "RegID",
                        "Алтайский край"});
            table3.AddRow(new string[] {
                        "OldTypeId",
                        "ВУЗ государственный"});
#line 29
 testRunner.And("вношу в поля следующие данные:", ((string)(null)), table3);
#line 33
 testRunner.And("нажимаю кнопку \"Найти\"");
#line 34
 testRunner.And("нажимаю кнопку \"Выбрать\"");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table4.AddRow(new string[] {
                        "selectedOrgName",
                        ""});
            table4.AddRow(new string[] {
                        "TBLastName",
                        ""});
            table4.AddRow(new string[] {
                        "TBFirstName",
                        ""});
            table4.AddRow(new string[] {
                        "TBPatronymicName",
                        ""});
            table4.AddRow(new string[] {
                        "TBMarkSum",
                        ""});
            table4.AddRow(new string[] {
                        "CodeNumberTextBox",
                        ""});
#line 35
 testRunner.And("вношу в поля следующие данные:", ((string)(null)), table4);
#line 43
 testRunner.And("нажимаю кнопку \"Проверить\"");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Value"});
            table5.AddRow(new string[] {
                        "Не заполнено поле \"Фамилия\""});
#line 44
 testRunner.Then("на экране есть:", ((string)(null)), table5);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Value"});
            table6.AddRow(new string[] {
                        "Не заполнено поле \"Имя\""});
#line 47
 testRunner.And("на экране есть:", ((string)(null)), table6);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Value"});
            table7.AddRow(new string[] {
                        "Не заполнено поле \"Сумма баллов\""});
#line 50
 testRunner.And("на экране есть:", ((string)(null)), table7);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Value"});
            table8.AddRow(new string[] {
                        "Выберите образовательное учреждение"});
#line 53
 testRunner.And("на экране есть:", ((string)(null)), table8);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Value"});
            table9.AddRow(new string[] {
                        "Необходимо выбрать не менее 3 предметов"});
#line 56
 testRunner.And("на экране есть:", ((string)(null)), table9);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05. Проверка очистки полей с помощью кнопки \"Очистить\"")]
        public virtual void _05_ПроверкаОчисткиПолейСПомощьюКнопкиОчистить()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05. Проверка очистки полей с помощью кнопки \"Очистить\"", ((string[])(null)));
#line 60
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 61
 testRunner.When("нажимаю кнопку \"Выбрать\"");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table10.AddRow(new string[] {
                        "RegID",
                        "Алтайский край"});
            table10.AddRow(new string[] {
                        "OldTypeId",
                        "ВУЗ государственный"});
#line 62
 testRunner.And("вношу в поля следующие данные:", ((string)(null)), table10);
#line 66
 testRunner.And("нажимаю кнопку \"Найти\"");
#line 67
 testRunner.And("нажимаю кнопку \"Выбрать\"");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table11.AddRow(new string[] {
                        "cLastName",
                        "test"});
            table11.AddRow(new string[] {
                        "cFirstName",
                        "test"});
            table11.AddRow(new string[] {
                        "cPatronymicName",
                        "test"});
            table11.AddRow(new string[] {
                        "cMarkSum",
                        "1234"});
            table11.AddRow(new string[] {
                        "CodeNumberTextBox",
                        "test"});
#line 68
 testRunner.And("вношу в поля следующие данные:", ((string)(null)), table11);
#line 75
 testRunner.And("выбираю чекбокс РУССКИЙ ЯЗЫК");
#line 76
 testRunner.And("выбираю чекбокс МАТЕМАТИКА");
#line 77
 testRunner.And("выбираю чекбокс ФИЗИКА");
#line 78
 testRunner.And("выбираю чекбокс ИСТОРИЯ");
#line 79
 testRunner.And("нажимаю кнопку \"Очистить\"");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table12.AddRow(new string[] {
                        "selectedOrgName",
                        "Выберите образовательное учреждение"});
            table12.AddRow(new string[] {
                        "cLastName",
                        "Фамилия"});
            table12.AddRow(new string[] {
                        "cFirstName",
                        "Имя"});
            table12.AddRow(new string[] {
                        "cPatronymicName",
                        "Отчество"});
            table12.AddRow(new string[] {
                        "cMarkSum",
                        "Сумма баллов"});
            table12.AddRow(new string[] {
                        "CodeNumberTextBox",
                        ""});
#line 80
 testRunner.Then("вижу в полях следующие данные:", ((string)(null)), table12);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06. Проверка  вывода результата \"Участник ЕГЭ найден\"")]
        public virtual void _06_ПроверкаВыводаРезультатаУчастникЕГЭНайден()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06. Проверка  вывода результата \"Участник ЕГЭ найден\"", ((string[])(null)));
#line 89
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 90
 testRunner.When("нажимаю кнопку \"Выбрать\"");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table13.AddRow(new string[] {
                        "RegID",
                        "Алтайский край"});
            table13.AddRow(new string[] {
                        "OldTypeId",
                        "ВУЗ государственный"});
#line 91
 testRunner.And("вношу в поля следующие данные:", ((string)(null)), table13);
#line 95
 testRunner.And("нажимаю кнопку \"Найти\"");
#line 96
 testRunner.And("нажимаю кнопку \"Выбрать\"");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table14.AddRow(new string[] {
                        "TBLastName",
                        "Плищук"});
            table14.AddRow(new string[] {
                        "TBFirstName",
                        "Роман"});
            table14.AddRow(new string[] {
                        "TBPatronymicName",
                        "Игоревич"});
            table14.AddRow(new string[] {
                        "TBMarkSum",
                        "285"});
            table14.AddRow(new string[] {
                        "CodeNumberTextBox",
                        ""});
#line 97
 testRunner.And("вношу в поля следующие данные:", ((string)(null)), table14);
#line 104
 testRunner.And("выбираю чекбокс РУССКИЙ ЯЗЫК");
#line 105
 testRunner.And("выбираю чекбокс МАТЕМАТИКА");
#line 106
 testRunner.And("выбираю чекбокс ХИМИЯ");
#line 107
 testRunner.And("выбираю чекбокс БИОЛОГИЯ");
#line 108
 testRunner.And("нажимаю кнопку \"Проверить\"");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Value",
                        "Value"});
            table15.AddRow(new string[] {
                        "Результат проверки",
                        "Участник ЕГЭ найден"});
            table15.AddRow(new string[] {
                        "Фамилия",
                        "Плищук"});
            table15.AddRow(new string[] {
                        "Имя",
                        "Роман"});
            table15.AddRow(new string[] {
                        "Отчество",
                        "Игоревич"});
            table15.AddRow(new string[] {
                        "Сумма баллов",
                        "285"});
#line 109
 testRunner.Then("на экране есть:", ((string)(null)), table15);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07.  Проверка вывода результата \"Участник ЕГЭ найден, но сумма баллов неверна\"")]
        public virtual void _07_ПроверкаВыводаРезультатаУчастникЕГЭНайденНоСуммаБалловНеверна()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07.  Проверка вывода результата \"Участник ЕГЭ найден, но сумма баллов неверна\"", ((string[])(null)));
#line 117
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 118
 testRunner.When("нажимаю кнопку \"Выбрать\"");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table16.AddRow(new string[] {
                        "RegID",
                        "Алтайский край"});
            table16.AddRow(new string[] {
                        "OldTypeId",
                        "ВУЗ государственный"});
#line 119
 testRunner.And("вношу в поля следующие данные:", ((string)(null)), table16);
#line 123
 testRunner.And("нажимаю кнопку \"Найти\"");
#line 124
 testRunner.And("нажимаю кнопку \"Выбрать\"");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table17.AddRow(new string[] {
                        "TBLastName",
                        "Плищук"});
            table17.AddRow(new string[] {
                        "TBFirstName",
                        "Роман"});
            table17.AddRow(new string[] {
                        "TBPatronymicName",
                        "Игоревич"});
            table17.AddRow(new string[] {
                        "TBMarkSum",
                        "290"});
            table17.AddRow(new string[] {
                        "CodeNumberTextBox",
                        ""});
#line 125
 testRunner.And("вношу в поля следующие данные:", ((string)(null)), table17);
#line 132
 testRunner.And("выбираю чекбокс РУССКИЙ ЯЗЫК");
#line 133
 testRunner.And("выбираю чекбокс МАТЕМАТИКА");
#line 134
 testRunner.And("выбираю чекбокс ХИМИЯ");
#line 135
 testRunner.And("выбираю чекбокс БИОЛОГИЯ");
#line 136
 testRunner.And("нажимаю кнопку \"Проверить\"");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Value",
                        "Value"});
            table18.AddRow(new string[] {
                        "Результат проверки",
                        "Участник ЕГЭ найден, но сумма баллов неверна"});
            table18.AddRow(new string[] {
                        "Фамилия",
                        "Плищук"});
            table18.AddRow(new string[] {
                        "Имя",
                        "Роман"});
            table18.AddRow(new string[] {
                        "Отчество",
                        "Игоревич"});
            table18.AddRow(new string[] {
                        "Сумма баллов",
                        "290"});
#line 137
 testRunner.Then("на экране есть:", ((string)(null)), table18);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("08.  Проверка вывода результата \"Участник ЕГЭ не найден\"")]
        public virtual void _08_ПроверкаВыводаРезультатаУчастникЕГЭНеНайден()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08.  Проверка вывода результата \"Участник ЕГЭ не найден\"", ((string[])(null)));
#line 145
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 146
 testRunner.When("нажимаю кнопку \"Выбрать\"");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table19.AddRow(new string[] {
                        "RegID",
                        "Алтайский край"});
            table19.AddRow(new string[] {
                        "OldTypeId",
                        "ВУЗ государственный"});
#line 147
 testRunner.And("вношу в поля следующие данные:", ((string)(null)), table19);
#line 151
 testRunner.And("нажимаю кнопку \"Найти\"");
#line 152
 testRunner.And("нажимаю кнопку \"Выбрать\"");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table20.AddRow(new string[] {
                        "TBLastName",
                        "Тестиков"});
            table20.AddRow(new string[] {
                        "TBFirstName",
                        "Тестик"});
            table20.AddRow(new string[] {
                        "TBPatronymicName",
                        "Тестикович"});
            table20.AddRow(new string[] {
                        "TBMarkSum",
                        "300"});
            table20.AddRow(new string[] {
                        "CodeNumberTextBox",
                        ""});
#line 153
 testRunner.And("вношу в поля следующие данные:", ((string)(null)), table20);
#line 160
 testRunner.And("выбираю чекбокс РУССКИЙ ЯЗЫК");
#line 161
 testRunner.And("выбираю чекбокс МАТЕМАТИКА");
#line 162
 testRunner.And("выбираю чекбокс ХИМИЯ");
#line 163
 testRunner.And("выбираю чекбокс БИОЛОГИЯ");
#line 164
 testRunner.And("нажимаю кнопку \"Проверить\"");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Value",
                        "Value"});
            table21.AddRow(new string[] {
                        "Результат проверки",
                        "Участник ЕГЭ не найден"});
            table21.AddRow(new string[] {
                        "Фамилия",
                        "Тестиков"});
            table21.AddRow(new string[] {
                        "Имя",
                        "Тестик"});
            table21.AddRow(new string[] {
                        "Отчество",
                        "Тестикович"});
            table21.AddRow(new string[] {
                        "Сумма баллов",
                        "300"});
#line 165
 testRunner.Then("на экране есть:", ((string)(null)), table21);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("09.  Проверка вывода результата \"Участник ЕГЭ найден, но баллы по заданным предме" +
            "там отсутствуют\"")]
        public virtual void _09_ПроверкаВыводаРезультатаУчастникЕГЭНайденНоБаллыПоЗаданнымПредметамОтсутствуют()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("09.  Проверка вывода результата \"Участник ЕГЭ найден, но баллы по заданным предме" +
                    "там отсутствуют\"", ((string[])(null)));
#line 173
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 174
 testRunner.When("нажимаю кнопку \"Выбрать\"");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table22.AddRow(new string[] {
                        "RegID",
                        "Алтайский край"});
            table22.AddRow(new string[] {
                        "OldTypeId",
                        "ВУЗ государственный"});
#line 175
 testRunner.And("вношу в поля следующие данные:", ((string)(null)), table22);
#line 179
 testRunner.And("нажимаю кнопку \"Найти\"");
#line 180
 testRunner.And("нажимаю кнопку \"Выбрать\"");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table23.AddRow(new string[] {
                        "TBLastName",
                        "Плищук"});
            table23.AddRow(new string[] {
                        "TBFirstName",
                        "Роман"});
            table23.AddRow(new string[] {
                        "TBPatronymicName",
                        "Игоревич"});
            table23.AddRow(new string[] {
                        "TBMarkSum",
                        "50"});
            table23.AddRow(new string[] {
                        "CodeNumberTextBox",
                        ""});
#line 181
 testRunner.And("вношу в поля следующие данные:", ((string)(null)), table23);
#line 188
 testRunner.And("выбираю чекбокс ИСТОРИЯ");
#line 189
 testRunner.And("выбираю чекбокс ГЕОГРАФИЯ");
#line 190
 testRunner.And("выбираю чекбокс ФРАНЦУЗСКИЙ ЯЗЫК");
#line 191
 testRunner.And("выбираю чекбокс ИНФОРМАТИКА И ИКТ");
#line 192
 testRunner.And("нажимаю кнопку \"Проверить\"");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Value",
                        "Value"});
            table24.AddRow(new string[] {
                        "Результат проверки",
                        "Участник ЕГЭ найден, но баллы по заданным предметам отсутствуют"});
            table24.AddRow(new string[] {
                        "Фамилия",
                        "Плищук"});
            table24.AddRow(new string[] {
                        "Имя",
                        "Роман"});
            table24.AddRow(new string[] {
                        "Отчество",
                        "Игоревич"});
            table24.AddRow(new string[] {
                        "Сумма баллов",
                        "50"});
#line 193
 testRunner.Then("на экране есть:", ((string)(null)), table24);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10.  Проверка работоспособности кнопки \"Вернуться назад\"")]
        public virtual void _10_ПроверкаРаботоспособностиКнопкиВернутьсяНазад()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10.  Проверка работоспособности кнопки \"Вернуться назад\"", ((string[])(null)));
#line 201
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 202
 testRunner.When("нажимаю кнопку \"Выбрать\"");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table25.AddRow(new string[] {
                        "RegID",
                        "Алтайский край"});
            table25.AddRow(new string[] {
                        "OldTypeId",
                        "ВУЗ государственный"});
#line 203
 testRunner.And("вношу в поля следующие данные:", ((string)(null)), table25);
#line 207
 testRunner.And("нажимаю кнопку \"Найти\"");
#line 208
 testRunner.And("нажимаю кнопку \"Выбрать\"");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table26.AddRow(new string[] {
                        "TBLastName",
                        "Плищук"});
            table26.AddRow(new string[] {
                        "TBFirstName",
                        "Роман"});
            table26.AddRow(new string[] {
                        "TBPatronymicName",
                        "Игоревич"});
            table26.AddRow(new string[] {
                        "TBMarkSum",
                        "50"});
            table26.AddRow(new string[] {
                        "CodeNumberTextBox",
                        ""});
#line 209
 testRunner.And("вношу в поля следующие данные:", ((string)(null)), table26);
#line 216
 testRunner.And("выбираю чекбокс ИСТОРИЯ");
#line 217
 testRunner.And("выбираю чекбокс ГЕОГРАФИЯ");
#line 218
 testRunner.And("выбираю чекбокс ФРАНЦУЗСКИЙ ЯЗЫК");
#line 219
 testRunner.And("выбираю чекбокс ИНФОРМАТИКА И ИКТ");
#line 220
 testRunner.And("нажимаю кнопку \"Проверить\"");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Value",
                        "Value"});
            table27.AddRow(new string[] {
                        "Результат проверки",
                        "Участник ЕГЭ найден, но баллы по заданным предметам отсутствуют"});
            table27.AddRow(new string[] {
                        "Фамилия",
                        "Плищук"});
            table27.AddRow(new string[] {
                        "Имя",
                        "Роман"});
            table27.AddRow(new string[] {
                        "Отчество",
                        "Игоревич"});
            table27.AddRow(new string[] {
                        "Сумма баллов",
                        "50"});
#line 221
 testRunner.Then("на экране есть:", ((string)(null)), table27);
#line 228
 testRunner.And("я нажимаю на ссылку \"Вернуться назад\"");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table28.AddRow(new string[] {
                        "selectedOrgName",
                        "Новоалтайский филиал Алтайского государственного технического университета им. И." +
                            "И. Ползунова"});
            table28.AddRow(new string[] {
                        "cLastName",
                        "Фамилия"});
            table28.AddRow(new string[] {
                        "cFirstName",
                        "Имя"});
            table28.AddRow(new string[] {
                        "cPatronymicName",
                        "Отчество"});
            table28.AddRow(new string[] {
                        "cMarkSum",
                        "Сумма баллов"});
            table28.AddRow(new string[] {
                        "CodeNumberTextBox",
                        ""});
#line 229
 testRunner.And("вижу в полях следующие данные:", ((string)(null)), table28);
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
