using System;
using System.Collections.Generic;

namespace Admin.Models.DBContext
{
    public partial class GzguTempResult
    {
        public int InstitutionId { get; set; }
        public int CompetitiveGroupId { get; set; }
        public int DirectionId { get; set; }
        public int EducationFormId { get; set; }
        public int EducationSourceId { get; set; }
        public int IdLevelBudget { get; set; }
        public int? _14 { get; set; }
        public int? _15 { get; set; }
        public int? _16 { get; set; }
        public int? _17 { get; set; }
        public int? _18 { get; set; }
        public int? _19 { get; set; }
        public int? _110 { get; set; }
        public int? _111 { get; set; }
        public int? _112 { get; set; }
        public int? _113 { get; set; }
        public int? _114 { get; set; }
        public int? _115 { get; set; }
        public int? _116 { get; set; }
        public int? _117 { get; set; }
        public int? _118 { get; set; }
        public int? _119 { get; set; }
        public int? _120 { get; set; }
        public int? _121 { get; set; }
        public int? _122 { get; set; }
        public int? _123 { get; set; }
        public int? _124 { get; set; }
        public int? _125 { get; set; }
        public int? _126 { get; set; }
        public int? _127 { get; set; }
        public int? _128 { get; set; }
        public int? _129 { get; set; }
        public int? _130 { get; set; }
        public int? _131 { get; set; }
        public int? _132 { get; set; }
        public int? _133 { get; set; }
        public int? _134 { get; set; }
        public int? _135 { get; set; }
        public int? _136 { get; set; }
        public int? _137 { get; set; }
        public int? _138 { get; set; }
        public int? _139 { get; set; }
        public int? _140 { get; set; }
        public int? _141 { get; set; }
        public int? _142 { get; set; }
        public int? _143 { get; set; }
        public int? _144 { get; set; }
        public int? _145 { get; set; }
        public int? _146 { get; set; }
        public int? _147 { get; set; }
        public int? _148 { get; set; }
        public decimal? _21 { get; set; }
        public int? _21Cnt { get; set; }
        public decimal? _22 { get; set; }
        public int? _22Cnt { get; set; }
        public decimal? _23 { get; set; }
        public int? _23Cnt { get; set; }
        public decimal? _24 { get; set; }
        public int? _24Cnt { get; set; }
        public decimal? _25 { get; set; }
        public int? _25Cnt { get; set; }
        public decimal? _26 { get; set; }
        public int? _26Cnt { get; set; }
        public decimal? _27 { get; set; }
        public int? _27Cnt { get; set; }
        public decimal? _28 { get; set; }
        public int? _28Cnt { get; set; }
        public decimal? _29 { get; set; }
        public decimal? _210 { get; set; }
        public decimal? _211 { get; set; }
        public decimal? _212 { get; set; }
        public decimal? _213 { get; set; }
        public decimal? _214 { get; set; }
        public int? _215 { get; set; }
        public int? _216 { get; set; }
        public int? _217 { get; set; }
        public int? _218 { get; set; }
        public int? _219 { get; set; }
        public int? _220 { get; set; }
        public decimal? _221 { get; set; }
        public int? _221Cnt { get; set; }
        public decimal? _222 { get; set; }
        public int? _222Cnt { get; set; }
        public decimal? _223 { get; set; }
        public int? _223Cnt { get; set; }
        public decimal? _224 { get; set; }
        public int? _224Cnt { get; set; }
        public decimal? _225 { get; set; }
        public int? _225Cnt { get; set; }
        public decimal? _226 { get; set; }
        public int? _226Cnt { get; set; }
        public int? _31 { get; set; }
        public int? _32 { get; set; }
        public int? _33 { get; set; }
        public int? _34 { get; set; }
        public int? _35 { get; set; }
        public int? _36 { get; set; }
        public int? _312 { get; set; }
        public int? _313 { get; set; }
        public int? _314 { get; set; }
        public int? _315 { get; set; }
        public int? _316 { get; set; }
        public int? _317 { get; set; }
        public int? _318 { get; set; }
        public int? _319 { get; set; }
        public int? _320 { get; set; }
        public int? _326 { get; set; }
        public int? _327 { get; set; }
        public int? _328 { get; set; }
        public decimal? _329 { get; set; }
        public int? _329Cnt { get; set; }
        public decimal? _330 { get; set; }
        public int? _330Cnt { get; set; }
        public decimal? _331 { get; set; }
        public int? _331Cnt { get; set; }
        public decimal? _332 { get; set; }
        public int? _332Cnt { get; set; }
        public decimal? _333 { get; set; }
        public int? _333Cnt { get; set; }
        public decimal? _334 { get; set; }
        public int? _334Cnt { get; set; }
        public decimal? _335 { get; set; }
        public int? _335Cnt { get; set; }
        public decimal? _336 { get; set; }
        public int? _336Cnt { get; set; }
        public decimal? _337 { get; set; }
        public int? _337Cnt { get; set; }
        public decimal? _338 { get; set; }
        public int? _338Cnt { get; set; }
        public decimal? _339 { get; set; }
        public int? _339Cnt { get; set; }
        public decimal? _340 { get; set; }
        public int? _340Cnt { get; set; }
        public decimal? _341 { get; set; }
        public int? _341Cnt { get; set; }
        public decimal? _342 { get; set; }
        public int? _342Cnt { get; set; }
        public int? _14Cnt { get; set; }
    }
}
