using System;
using System.Collections.Generic;

namespace Admin.Models.DBContext
{
    public partial class GzgubackFull20172016
    {
        public int Id { get; set; }
        public string Inn { get; set; }
        public string Kpp { get; set; }
        public string InsName { get; set; }
        public string DirCode { get; set; }
        public string _11 { get; set; }
        public string _12 { get; set; }
        public string _13 { get; set; }
        public string _14 { get; set; }
        public string _15 { get; set; }
        public string _16 { get; set; }
        public string _17 { get; set; }
        public string _18 { get; set; }
        public string _19 { get; set; }
        public string _110 { get; set; }
        public string _111 { get; set; }
        public string _112 { get; set; }
        public string _113 { get; set; }
        public string _114 { get; set; }
        public string _115 { get; set; }
        public string _116 { get; set; }
        public string _117 { get; set; }
        public string _118 { get; set; }
        public string _119 { get; set; }
        public string _120 { get; set; }
        public string _124 { get; set; }
        public string _125 { get; set; }
        public string _126 { get; set; }
        public string _127 { get; set; }
        public string _128 { get; set; }
        public string _129 { get; set; }
        public string _130 { get; set; }
        public string _131 { get; set; }
        public string _132 { get; set; }
        public string _133 { get; set; }
        public string _134 { get; set; }
        public string _135 { get; set; }
        public string _136 { get; set; }
        public string _137 { get; set; }
        public string _138 { get; set; }
        public string _139 { get; set; }
        public string _140 { get; set; }
        public string _141 { get; set; }
        public string _142 { get; set; }
        public string _143 { get; set; }
        public string _144 { get; set; }
        public string _145 { get; set; }
        public string _146 { get; set; }
        public string _147 { get; set; }
        public string _148 { get; set; }
        public string _21 { get; set; }
        public string _22 { get; set; }
        public string _23 { get; set; }
        public string _24 { get; set; }
        public string _25 { get; set; }
        public string _26 { get; set; }
        public string _27 { get; set; }
        public string _28 { get; set; }
        public string _29 { get; set; }
        public string _210 { get; set; }
        public string _211 { get; set; }
        public string _212 { get; set; }
        public string _213 { get; set; }
        public string _214 { get; set; }
        public string _215 { get; set; }
        public string _216 { get; set; }
        public string _217 { get; set; }
        public string _218 { get; set; }
        public string _219 { get; set; }
        public string _220 { get; set; }
        public string _221 { get; set; }
        public string _222 { get; set; }
        public string _223 { get; set; }
        public string _224 { get; set; }
        public string _225 { get; set; }
        public string _226 { get; set; }
        public string _31 { get; set; }
        public string _32 { get; set; }
        public string _33 { get; set; }
        public string _34 { get; set; }
        public string _35 { get; set; }
        public string _36 { get; set; }
        public string _312 { get; set; }
        public string _313 { get; set; }
        public string _314 { get; set; }
        public string _315 { get; set; }
        public string _316 { get; set; }
        public string _317 { get; set; }
        public string _318 { get; set; }
        public string _319 { get; set; }
        public string _320 { get; set; }
        public string _326 { get; set; }
        public string _327 { get; set; }
        public string _329 { get; set; }
        public string _330 { get; set; }
        public string _331 { get; set; }
        public string _332 { get; set; }
        public string _333 { get; set; }
        public string _334 { get; set; }
        public string _336 { get; set; }
        public string _337 { get; set; }
        public string _338 { get; set; }
        public string _339 { get; set; }
        public string _340 { get; set; }
        public string _341 { get; set; }
    }
}
